steps:
  # Build the Docker image
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/my-python-app:$SHORT_SHA
      - .

  # Push the image to GCR
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - gcr.io/$PROJECT_ID/my-python-app:$SHORT_SHA
    waitFor:
      - "Build"

images:
  - gcr.io/$PROJECT_ID/my-python-app:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY